### ISSUE TITLE
AlgorithmIdentifier there can be 1 element in cert

### ISSUE THREAD

**Issue by svkreml** [JonathanWilbur/x509-ts#2]
SEQUENCE (1 elem)
      OBJECT IDENTIFIER 1.2.643.2.2.3
[example](https://lapo.it/asn1js/#MIIFGTCCBMigAwIBAgIQNGgeQMtB7zOpoLfIdpKaKTAIBgYqhQMCAgMwggFKMR4wHAYJKoZIhvcNAQkBFg9kaXRAbWluc3Z5YXoucnUxCzAJBgNVBAYTAlJVMRwwGgYDVQQIDBM3NyDQsy4g0JzQvtGB0LrQstCwMRUwEwYDVQQHDAzQnNC-0YHQutCy0LAxPzA9BgNVBAkMNjEyNTM3NSDQsy4g0JzQvtGB0LrQstCwLCDRg9C7LiDQotCy0LXRgNGB0LrQsNGPLCDQtC4gNzEsMCoGA1UECgwj0JzQuNC90LrQvtC80YHQstGP0LfRjCDQoNC-0YHRgdC40LgxGDAWBgUqhQNkARINMTA0NzcwMjAyNjcwMTEaMBgGCCqFAwOBAwEBEgwwMDc3MTA0NzQzNzUxQTA_BgNVBAMMONCT0L7Qu9C-0LLQvdC-0Lkg0YPQtNC-0YHRgtC-0LLQtdGA0Y_RjtGJ0LjQuSDRhtC10L3RgtGAMB4XDTEyMDcyMDEyMzExNFoXDTI3MDcxNzEyMzExNFowggFKMR4wHAYJKoZIhvcNAQkBFg9kaXRAbWluc3Z5YXoucnUxCzAJBgNVBAYTAlJVMRwwGgYDVQQIDBM3NyDQsy4g0JzQvtGB0LrQstCwMRUwEwYDVQQHDAzQnNC-0YHQutCy0LAxPzA9BgNVBAkMNjEyNTM3NSDQsy4g0JzQvtGB0LrQstCwLCDRg9C7LiDQotCy0LXRgNGB0LrQsNGPLCDQtC4gNzEsMCoGA1UECgwj0JzQuNC90LrQvtC80YHQstGP0LfRjCDQoNC-0YHRgdC40LgxGDAWBgUqhQNkARINMTA0NzcwMjAyNjcwMTEaMBgGCCqFAwOBAwEBEgwwMDc3MTA0NzQzNzUxQTA_BgNVBAMMONCT0L7Qu9C-0LLQvdC-0Lkg0YPQtNC-0YHRgtC-0LLQtdGA0Y_RjtGJ0LjQuSDRhtC10L3RgtGAMGMwHAYGKoUDAgITMBIGByqFAwICIwEGByqFAwICHgEDQwAEQI-lv3kQI8jWka1kMVdbvpvFioP0Pyn3Knmp-2XD6KgPWnXEIlSRX8g_IYracDr51YsNc2KE3C7mkH6hA3M3ofujggGCMIIBfjCBxgYFKoUDZHAEgbwwgbkMI9Cf0JDQmtCcIMKr0JrRgNC40L_RgtC-0J_RgNC-IEhTTcK7DCDQn9CQ0JogwqvQk9C-0LvQvtCy0L3QvtC5INCj0KbCuww20JfQsNC60LvRjtGH0LXQvdC40LUg4oSWIDE0OS8zLzIvMi05OTkg0L7RgiAwNS4wNy4yMDEyDDjQl9Cw0LrQu9GO0YfQtdC90LjQtSDihJYgMTQ5LzcvMS80LzItNjAzINC-0YIgMDYuMDcuMjAxMjAuBgUqhQNkbwQlDCPQn9CQ0JrQnCDCq9Ca0YDQuNC_0YLQvtCf0YDQviBIU03CuzBDBgNVHSAEPDA6MAgGBiqFA2RxATAIBgYqhQNkcQIwCAYGKoUDZHEDMAgGBiqFA2RxBDAIBgYqhQNkcQUwBgYEVR0gADAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH_BAUwAwEB_zAdBgNVHQ4EFgQUi5g7iRhR6O-cAni46sjUILJVyV0wCAYGKoUDAgIDA0EA23Reec_Y27rpMi-iFbgWCazGY3skBTq5ZGsQKOUxCe4mO7UBDACiWqdA0nvqiQMXeHgqo__fO9pxuIHtymwyMg)

    public static fromElement(value: DERElement): AlgorithmIdentifier {
	        const algorithmIdentifierElements: DERElement[] = value.sequence;
	        if (algorithmIdentifierElements.length > 2)
	            throw new errors.X509Error('Invalid number of elements in AlgorithmIdentifier');
	        switch (algorithmIdentifierElements[0].validateTag(
	            [ ASN1TagClass.universal ],
            [ ASN1Construction.primitive ],
            [ ASN1UniversalType.objectIdentifier ])
        ) {
            case 0: break;
            case -1: throw new errors.X509Error('Invalid tag class on AlgorithmIdentifier.algorithm');
            case -2: throw new errors.X509Error('Invalid construction on AlgorithmIdentifier.algorithm');
	            case -3: throw new errors.X509Error('Invalid tag number on AlgorithmIdentifier.algorithm');
	            default: throw new errors.X509Error('Undefined error when validating AlgorithmIdentifier.algorithm tag');
	        }
	        if (algorithmIdentifierElements.length === 1){
	            return new AlgorithmIdentifier(
	                algorithmIdentifierElements[0].objectIdentifier);
	        }
	        return new AlgorithmIdentifier(
	            algorithmIdentifierElements[0].objectIdentifier,
	            algorithmIdentifierElements[1]
        );
    }

**Comment by JonathanWilbur** [comment]
Fixed in version 0.11.7, which is now published. Thanks for reporting this!
