### ISSUE TITLE
Validity.ts 

### ISSUE THREAD

**Issue by svkreml** [JonathanWilbur/x509-ts#3]
https://github.com/xaptum/xtt/issues/64

public toElement(): DERElement {

	        /*
	        CAs conforming to this profile MUST always encode certificate
	        validity dates through the year 2049 as UTCTime; certificate validity
	        dates in 2050 or later MUST be encoded as GeneralizedTime.
	        Conforming applications MUST be able to process validity dates that
	        are encoded in either UTCTime or GeneralizedTime.
	        * */
	
	        const notBeforeElement: DERElement = new DERElement();
	        notBeforeElement.tagNumber = ASN1UniversalType.generalizedTime;
	        notBeforeElement.generalizedTime = this.notBefore;
	        if (this.notBefore.getFullYear() < 2049) {
	            notBeforeElement.utcTime = this.notBefore;
	            notBeforeElement.tagNumber = ASN1UniversalType.utcTime;
	        } else {
	            notBeforeElement.generalizedTime = this.notBefore;
	            notBeforeElement.tagNumber = ASN1UniversalType.generalizedTime;
	        }
	
	        const notAfterElement: DERElement = new DERElement();
	        notAfterElement.tagNumber = ASN1UniversalType.generalizedTime;
	        notAfterElement.generalizedTime = this.notBefore;
	        if (this.notAfter.getFullYear() < 2049) {
	            notAfterElement.utcTime = this.notAfter;
	            notAfterElement.tagNumber = ASN1UniversalType.utcTime;
	        } else {
	            notAfterElement.generalizedTime = this.notAfter;
	            notAfterElement.tagNumber = ASN1UniversalType.generalizedTime;
	        }

I'm trying to make cert reading and then writing back to der binnary the same

https://github.com/svkreml/miniCa/blob/ts-x509/src/app/x509-ts-master/test/karma/x509-ts.spec.ts

**Comment by JonathanWilbur** [comment]
So you know, I have pushed a commit that fixed this (tagged `v0.11.8`), but because of (I think) a bug in GitHub Actions (which is still in beta), it has not been attached to `HEAD` of `master`. I am going to pause my work on these issues until I hear back from GitHub so I do not corrupt my repository, but I will return to this and your other remaining issue within the week, even if I do not hear back from them by then. Thanks again for reporting these.

**Comment by JonathanWilbur** [comment]
I have already published this version and I figured out the issue with Git--a workaround anyway.
