### ISSUE TITLE
Recreating cert Extensions do not work

### ISSUE THREAD

**Issue by svkreml** [JonathanWilbur/x509-ts#4]
https://github.com/svkreml/miniCa/commit/6297a1e640a3f293affd30b2fa92fa15c2febb4f

When writing cert back to der it writes empty ext elements

There is extesions in your library, but by default fromElement do not choose from them, maybe there is need of switch case mechanism of finding that classes by oid, so certificate object would be without unparsed data, with current class that store binary ext data as default 

You can see here what i do to make it work for me, its hard to explain, but test  for recreating rsa cert works

And maybe this will be a good idea to do so that all these classes are inherited from the base?

you can have an array of typed extensions and they all can be coded/decoded by the same interface

**Comment by svkreml** [comment]
And when reading cert as i see in certs 'critical' may be absent

**Comment by JonathanWilbur** [comment]
Fixed with version 0.11.9, which is now published. Thanks for reporting these! I really appreciate your help!
