### ISSUE TITLE
cant import Extensions from 'x509-ts'

### ISSUE THREAD

**Issue by svkreml** [JonathanWilbur/x509-ts#5]
Hello, I cant use
  _import Extensions from 'x509-ts';_
only
  _import Extensions from 'x509-ts/dist/AuthenticationFramework/Extensions';_
works

possible solution: 
  _add export { default as Extensions } from "./Extensions";_
to 
  _node_modules/x509-ts/dist/AuthenticationFramework/index.d.ts_

**Comment by JonathanWilbur** [comment]
Fixed in version 0.11.10, which is now published.
