### ISSUE TITLE
KeyIdentifier do not get encoded by method toElement()

### ISSUE THREAD

**Issue by svkreml** [JonathanWilbur/x509-ts#7]
Hello again.

class AuthorityKeyIdentifier

value _this.keyIdentifier_ do not get encoded in method _toElement_

You are creating element, but do not put in it _this.keyIdentifier_

        const keyIdentifierElement: DERElement = new DERElement(
            ASN1TagClass.context,
            ASN1Construction.primitive,
            0
        );

From what i understand we want somethig like
```
        SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.35 authorityKeyIdentifier (X.509 extension)
          OCTET STRING (1 elem)
            SEQUENCE (1 elem)
              [0] (20 byte) F825D9A639C7C38187253E3054911821409B179D
```

but getting
```
        SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.35 authorityKeyIdentifier (X.509 extension)
          OCTET STRING (1 elem)
            SEQUENCE (1 elem)
              [0]
```

P.S.

You make SubjectKeyIdentifier as Uint8Array, but to make it work i need to wrap it in another OctetString
```
        SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.14 subjectKeyIdentifier (X.509 extension)
          OCTET STRING (1 elem)
            OCTET STRING (20 byte) DE7F7FE67CEDED61436047675D862F84FDA678AD
```

P.P.S. 
How you still stand me with me creating all that issues?)

**Comment by JonathanWilbur** [comment]
Fixed in version 0.11.12, which is now published. As always, thanks for reporting! You are not a problem at all; your bug reports help me!
